print("H")
print("He")
print("Hel")
print("Hell")
print("Hello")
print("Hello W")
print("Hello Wo")
print("Hello Wor")
print("Hello Worl")
print("Hello World")
print("Hello World!")
print("Hello World")
print("Hello Worl")
print("Hello Wor")
print("Hello Wo")
print("Hello W")
print("Hello")
print("Hell")
print("Hel")
print("He")
print("H")
